# Generated by Django 4.2.21 on 2025-06-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipo_usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
